# Generated by Django 5.1.1 on 2024-12-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FireSmokeAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='alerts/')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
